# Generated by Django 4.1.1 on 2022-09-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mouses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('producto', models.TextField(null=True, verbose_name='Productoo')),
                ('img', models.TextField(null=True, verbose_name='link de la image')),
                ('precio', models.IntegerField(max_length=10, verbose_name='Precio')),
            ],
        ),
    ]
