# Generated by Django 4.1.1 on 2022-10-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouses',
            name='categorias',
            field=models.CharField(choices=[('MS', 'Mouses'), ('TC', 'Teclados'), ('MN', 'Monitores'), ('MP', 'Mouse pad'), ('DD', 'Diademas')], default='MS', max_length=2),
        ),
        migrations.AlterField(
            model_name='mouses',
            name='img',
            field=models.TextField(max_length=10, null=True, verbose_name='link de la image'),
        ),
        migrations.AlterField(
            model_name='mouses',
            name='precio',
            field=models.IntegerField(null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='mouses',
            name='producto',
            field=models.TextField(max_length=10, null=True, verbose_name='Productoo'),
        ),
    ]
